name: AdGuard DNS filter

on: workflow_dispatch

jobs:
  extract_lines:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Extract lines and create DNS file
        run: |
          python - <<EOF
          import requests
          import os

          url = "https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt"
          response = requests.get(url)
          lines = response.text.split("\n")

          # 过滤出以 "||" 开头的行
          filtered_lines = [line[2:-1] for line in lines if line.startswith("||")]

          # 创建 dns.yaml 文件
          output_dir = "autoupdate"
          os.makedirs(output_dir, exist_ok=True)
          output_file = os.path.join(output_dir, "AdGuard.yaml")

          with open(output_file, "w") as f:
              f.write("payload:\n")
              f.write(f"  #get {len(filtered_lines)} domain from AdGuard DNS filter\n")
              
              for line in filtered_lines:
                  f.write(f"  - '+.{line}'\n")

          print("Extraction complete.")
          EOF
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add autoupdate/AdGuard.yaml
          git commit -m "AdGuard DNS filter"
          git push
