name: AdGuard DNS filter

on: workflow_dispatch

jobs:
  extract_domains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Fetch filter.txt
        run: |
          curl -o filter.txt https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

      - name: Extract domains
        id: extract
        run: |
          cat filter.txt | grep '^\|\|' | awk -F '^\|\|' '{print $2}' | sed 's/\^//' > domains.txt
          total_domains=$(wc -l < domains.txt)

      - name: Create dns.yaml
        run: |
          echo "payload:" > autoupdate/AdGuard.yaml
          echo "  #get $total_domains domain" >> autoupdate/AdGuard.yaml
          echo "  " >> autoupdate/AdGuard.yaml
          while IFS= read -r line; do
            echo "  - '+.$line'" >> autoupdate/AdGuard.yaml
          done < domains.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add autoupdate/AdGuard.yaml
          git commit -m "AdGuard"
          git push
