name: Update gfw.mrs

on:
  schedule:
    # 每天北京时间上午8点运行 (UTC时间0点)
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update-gfw-mrs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create autoupdate directory if not exists
        run: mkdir -p autoupdate

      - name: Download gfw.yaml
        run: |
          curl -sSL -o autoupdate/gfw.yaml https://raw.githubusercontent.com/ameyukisora/Clash-Rule/refs/heads/master/autoupdate/gfw.yaml

      - name: Download mihomo
        run: |
          MIHOMO_VERSION="v1.19.11" # 可以根据需要修改版本
          ARCH="amd64" # 根据运行环境选择架构，例如 "arm64", "armv7", "386", "amd64"
          wget -qO- "https://github.com/MetaCubeX/mihomo/releases/download/${MIHOMO_VERSION}/mihomo-linux-${ARCH}-${MIHOMO_VERSION}.gz" | gzip -d > mihomo
          chmod +x mihomo

      - name: Convert gfw.yaml to gfw.mrs
        run: |
          ./mihomo convert-ruleset domain yaml autoupdate/gfw.yaml autoupdate/gfw.mrs

      - name: Commit and push changes
        run: |
          if [[ $(git status --porcelain autoupdate/gfw.mrs) ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add autoupdate/*.mrs
            git commit -m "$(date -u +"%Y-%m-%d %H:%M:%S" -d "+8 hours")"
            git push
          else
            echo "No changes to commit."
          fi