# 工作流名称
name: Convert GFW Rule to MRS

on:
  # 允许在 Actions 页面手动触发此工作流
  workflow_dispatch:

  # 设置定时任务，使用 Cron 表达式
  # 每天在北京时间早上 5 点执行 (UTC 时间为前一天 21:00)
  schedule:
    - cron: '0 21 * * *'

jobs:
  build-and-commit:
    # 使用最新版的 Ubuntu 虚拟机
    runs-on: ubuntu-latest

    steps:
      # 步骤1: 检出你的仓库代码
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 步骤2: 创建用于存放 mrs 文件的目录
      - name: Create autoupdate directory
        run: mkdir -p ./autoupdate

      # 步骤3: 下载 gfw.yaml 文件
      - name: Download gfw.yaml
        run: curl -L -o gfw.yaml https://raw.githubusercontent.com/ameyukisora/Clash-Rule/master/autoupdate/gfw.yaml

      # 步骤4: 安装 mihomo 内核 (最终优化版)
      # 精准过滤，只选择一个标准的 .gz 文件，并用 first 确保输出唯一
      - name: Set up mihomo
        run: |
          MIHOMO_URL=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/MetaCubeX/mihomo/releases/latest" | \
            jq -r '(.assets[] | select(.name | contains("linux-amd64") and endswith(".gz") and (contains("compatible") | not)) | .browser_download_url) | first')
          
          if [ -z "$MIHOMO_URL" ]; then
            echo "错误：无法找到 mihomo linux-amd64 的下载链接。"
            exit 1
          fi

          echo "正在从以下链接下载 mihomo: $MIHOMO_URL"
          wget -q -O mihomo-linux-amd64.gz "$MIHOMO_URL"
          gunzip mihomo-linux-amd64.gz
          chmod +x mihomo-linux-amd64
          sudo mv mihomo-linux-amd64 /usr/local/bin/mihomo

      # 步骤5: 将 YAML 转换为 .mrs
      - name: Convert YAML to .mrs
        run: mihomo convert-ruleset domain yaml gfw.yaml ./autoupdate/gfw.mrs

      # 步骤6: 自动提交并推送到你的仓库
      - name: Commit and push .mrs file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: 自动更新 gfw.mrs 规则"
          file_pattern: "./autoupdate/gfw.mrs"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
