name: Convert YAML to MRS

on:
  schedule:
    # 每天凌晨 00:00 UTC 运行
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Mihomo
        run: |
          MIHOMO_VERSION="v1.19.11" # 可以根据需要修改 Mihomo 版本
          wget -qO- "https://github.com/MetaCubeX/mihomo/releases/download/${MIHOMO_VERSION}/mihomo-linux-amd64-${MIHOMO_VERSION}.gz" | gzip -d > mihomo
          chmod +x mihomo

      - name: Create autoupdate directory if it doesn't exist
        run: mkdir -p autoupdate

      - name: Download gfw.yaml
        run: |
          wget -O autoupdate/gfw.yaml https://raw.githubusercontent.com/ameyukisora/Clash-Rule/refs/heads/master/autoupdate/gfw.yaml

      - name: Convert gfw.yaml to gfw.mrs
        run: |
          ./mihomo convert-ruleset domain yaml autoupdate/gfw.yaml autoupdate/gfw.mrs

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[mrs]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add autoupdate/gfw.mrs
          git commit -m "Update gfw.mrs" || echo "No changes to commit"
          git push
