name: Fetch and Convert chnroutes.txt

on: workflow_dispatch

jobs:
  fetch_convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch chnroutes.txt
      run: |
        curl -o chnroutes.txt https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt
        mkdir -p Clash-Rule/provider
        mv chnroutes.txt Clash-Rule/provider
        sed -i '1s/^/payload:\n/' Clash-Rule/provider/chnroutes.txt
        sed -i '2,${s/^- /  - /}' Clash-Rule/provider/chnroutes.txt
        sed -i '/^  - / s/$/\r/' Clash-Rule/provider/chnroutes.txt
        mv Clash-Rule/provider/chnroutes.txt Clash-Rule/provider/chnroutes.yaml
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Clash-Rule/provider/chnroutes.yaml
        git commit -m "Update chnroutes.yaml"
        git push
