name: misakaio chnroutes2

on:
  schedule:
    - cron: "30 17 * * *"

  workflow_dispatch:

jobs:
  fetch_and_convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main
      
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: chnroutes2 convert yaml
        run: |
          python - <<EOF
          import requests
          import os

          url = "https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt"
          response = requests.get(url)
          lines = response.text.split("\n")

          # filter out empty elements
          lines = list(filter(None, lines))

          # create file
          os.makedirs("autoupdate", exist_ok=True)
          output_file = "autoupdate/chnroutes.yaml"

          output_lines = [
              "payload:",
              "  # https://github.com/misakaio/chnroutes2",
              f"  {lines[0]}",
              f"  {lines[1]}"
          ]
          output_lines.extend([f"  - '{line}'" for line in lines[2:]])

          with open(output_file, "w") as f:
             f.write("\n".join(output_lines))

          EOF
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add autoupdate/*.yaml
          git commit -m "$(date -u +"%Y-%m-%d %H:%M:%S" -d "+8 hours")"
          git push
