name: Fetch and Convert chnroutes.txt

on:
  schedule:
    - cron: "30 20 * * *"

  workflow_dispatch:

jobs:
  fetch_and_convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Fetch chnroutes.txt
      run: curl -o chnroutes.txt https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt

    - name: Convert and Save to autoupdate
      run: |
        echo 'payload:' > chnroutes.yaml
        echo '  # https://github.com/misakaio/chnroutes2' >> chnroutes.yaml
        sed -n '1,2p' chnroutes.txt | sed 's/.*/  ''&''/' >> chnroutes.yaml
        sed -n '3,$p' chnroutes.txt | sed 's/.*/  - '\''&'\''/' >> chnroutes.yaml
        mkdir -p autoupdate
        mv chnroutes.yaml autoupdate/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add autoupdate/chnroutes.yaml
        git commit -m "misakaio chnroutes2"
        git push
