name: Squash Actions User Commits

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:  # 允许手动触发

jobs:
  squash-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Squash actions-user commits
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        
        # 获取最新的非 actions-user commit
        LAST_HUMAN_COMMIT=$(git log --author="^((?!github-actions).)*$" --pretty=format:"%H" -n 1)
        
        # 获取最新的 actions-user commit
        LAST_ACTION_COMMIT=$(git log --author="github-actions" --pretty=format:"%H" -n 1)
        
        if [ -n "$LAST_HUMAN_COMMIT" ] && [ -n "$LAST_ACTION_COMMIT" ]; then
          # 创建一个临时分支
          git checkout -b temp_branch $LAST_HUMAN_COMMIT
          
          # 应用最新的 actions-user commit
          git cherry-pick $LAST_ACTION_COMMIT
          
          # 强制更新 main 分支
          git branch -f main temp_branch
          git checkout main
          git branch -D temp_branch
          
          # 强制推送到远程仓库
          git push -f origin main
        else
          echo "No commits to squash"
        fi
